name       : lsp-plugins
version    : 1.1.31
release    : 6
source     :
    - https://github.com/sadko4u/lsp-plugins/archive/refs/tags/1.1.31.tar.gz : 1c7327072913b3d95902d1a7c6cdac77d733099abf6616005544cea5e24f567e
license    : LGPL-3.0-only
component  : multimedia.audio
summary    : Linux Studio Plugins Project
description: |
    LSP (Linux Studio Plugins) is a collection of open-source plugins
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
    - ladspa-devel
build      : |
    %make BUILD_MODULES='ladspa lv2 vst jack' PREFIX=/usr LIBDIR=%libdir%
install    : |
    %make_install
