name       : lsp-plugins
version    : 1.1.21
release    : 3
source     :
    - https://github.com/sadko4u/lsp-plugins/archive/lsp-plugins-1.1.21.tar.gz : 63702d0326d2bbfc2c9afdceb33923e06fd43f477e8eab5900ff04b0646560e8
license    : LGPL-3.0-only
component  : multimedia.audio
summary    : Linux Studio Plugins Project
description: |
    LSP (Linux Studio Plugins) is a collection of open-source plugins
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
    - ladspa-devel
build      : |
    %make BUILD_MODULES='ladspa lv2 vst jack' PREFIX=/usr
install    : |
    %make_install
