name       : lsp-plugins
version    : 1.2.1
release    : 7
source     :
    - https://github.com/sadko4u/lsp-plugins/releases/download/1.2.1/lsp-plugins-src-1.2.1.tar.gz : c0789b6496eb832eedd33dab4437b5154006dfc056fdd474260a0a5566029fad
license    : LGPL-3.0-only
component  : multimedia.audio
summary    : Linux Studio Plugins Project
description: |
    LSP (Linux Studio Plugins) is a collection of open-source plugins
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
    - ladspa-devel
setup      : |
    make config FEATURES='ladspa lv2 vst2 jack' PREFIX=/usr LIBDIR=%libdir%
build      : |
    %make
install    : |
    %make_install
